### ISSUE TITLE
Add an option to automaticly apply updates

### ISSUE THREAD

**Issue by Tuquilo9** [Antiz96/arch-update#222] opened 2024-07-31 14:48 UTC
### Description

This setting can be changed in the arch-update config file and when activated, after reading all updates' infos, the updates will be applied automaticly. For example 'pacman -Syu' will be run with the '--noconfirm' option

### Motivation and context

I think this feature is usefull because when you leave your computer the updates will continue, even flatpaks, AURs, ...

Sorry for my English!

**Comment by Antiz96** [comment] 2024-07-31 21:32
Hi,

Thanks a lot for the feature request!
However, I'm not really up for this to be honest... 

The usage of `--noconfirm` is actually discouraged (from the [pacman man page](https://man.archlinux.org/man/pacman.8.en.html): "It’s not a good idea to do this unless you want to run pacman from a script"). 
I understand that pacman's confirmation may feel like a duplicate of the first confirmation Arch-Update asks you after printing the list of pending update. But the initial list printed by Arch-Update only contains the **installed** package that will be updated while the list printed by pacman afterwards may be slightly different (for instance if the update of a specific package implies to install new dependencies), which could justify a double confirmation (also, a double confirmation never hurts in my opinion :stuck_out_tongue:).

More generally speaking, Arch-Update has been designed to follow [Arch Linux system maintenance](https://wiki.archlinux.org/title/System_maintenance) advice and, as such, is not meant to be run non-interactively. Indeed, Arch Linux advises [to read pacman output](https://wiki.archlinux.org/title/System_maintenance#Act_on_alerts_during_an_upgrade) to pay attention to the eventual alert notices provided during packages updates, which is not really compatible with one leaving the computer while updates are applied.
With Arch Linux itself discouraging/not supporting automatic updates, I don't want to support it at the Arch-Update level. I'd like Arch-Update to be a "helper" rather than a "decision maker".

I hope you get the point! :slightly_smiling_face: 
Now... one could still run `yes | arch-update` to automatically answer "yes" to **every** questions asked by Arch-Update, but I would personally not recommend that (as it may perform undesired actions), so use it at your own risks :sweat_smile: 

Regardless, thanks once again for your request and your overall interest in Arch-Upate! :smile:

**Closed by Antiz96** 2024-07-31 21:32 UTC
Labels: feature/request
