### ISSUE TITLE
Systray appplet tooltip not available in Gnome desktop?

### ISSUE THREAD

**Issue by DeN-AlB** [Antiz96/arch-update#260] opened 2024-10-02 09:43 UTC
### Environment

- Distribution: EndeavourOS Gnome
- Arch-Update version: 3.2.0 from AUR

### Arch-Update configuration

No arch-update.conf configuration file in use.

### Description of the bug

I'm using Gnome desktop with extension "AppIndicator and KStatusNotifierItem Support" installed and enabled. So there are systray icons available.

There is a notification popping up when new updates are available.

![image](https://github.com/user-attachments/assets/92e8740e-c3b5-40a5-86af-9a048cbc81d1)

But I don't get the systray applet tooltip when hovering the mouse over the systray icon.

![image](https://github.com/user-attachments/assets/52d64023-80fe-4787-a9fb-c73158d151a8)

I only get the context menu when right-clicking on the systray icon.

![image](https://github.com/user-attachments/assets/9656d525-4b1a-4b55-9f1d-eaddce9e64cc)

I tried removing and reinstalling arch-update, but it didn't change.

What could be the reason?

**Comment by Antiz96** [comment] 2024-10-02 11:18
Hi,

Thanks for the report!

Unfortunately, as you know, Gnome does not support systray applet out of the box and has to rely on a third party extension to do so (as you said in your report).

I have tested the tooltip successfully on Kde, Xfce & Sway (with both waybar and nwg-panel), which means the tooltip itself it definitely working as intended. This might indicate that the issue is directly from "AppIndicator and KStatusNotifierItem Support" extension, in which case I won't be able to do much on my side unfortunately...

I'll still set up a test environment running Gnome later today and make some analyses. I'll let you know!

**Comment by DeN-AlB** [comment] 2024-10-02 13:40
> This might indicate that the issue is directly from the "AppIndicator and KStatusNotifierItem Support" extension, in which case I won't be able to do much on my side unfortunately...

Good to know. So I'll have to try to create a bug report or a feature request on the extension side ...

> I'll still set up a test environment running Gnome later today and make some analyses. I'll let you know!

Great! I'm looking forward to your results. :smile:

**Comment by Antiz96** [comment] 2024-10-02 15:19
Ok so... I'm afraid I have some bad news :no_mouth: 

It became quite clear pretty fast that the issue is coming from the "AppIndicator and KStatusNotifierItem Support" extension when I saw some differences from the default / expected behavior and the extension's behavior (for instance, clicking the systray applet is supposed to run Arch-Update, while doing so with the extension opens the "right click" menu instead).

I searched a bit in the upstream repo and found [this commit](https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/7f66b531ab6e9a9cdf5bf48196a3b529db42e58c) which disables tooltip related properties, stating that they do not support tooltips.

So, unless it exists another extension that provides systrays support for Gnome and that supports tooltips, I'm afraid Gnome users won't be able to see Arch-Update's tooltip... 😕

**Comment by Antiz96** [comment] 2024-10-02 15:34
Allow me to close this issue then. As said above, Gnome does not support systray applets by default and the third party extension required to bring it doesn't support tooltips itself... There's unfortunately not much I can do about it at my level.

Sorry about that :confused:

**Comment by Antiz96** [comment] 2024-10-02 15:40
Just as a complementary information, the fact that tooltips are unsupported by the extension is actually documented in their README at https://github.com/ubuntu/gnome-shell-extension-appindicator?tab=readme-ov-file#missing-features

**Comment by Antiz96** [comment] 2024-10-02 15:46
Just as a complementary information, the fact that tooltips are unsupported by the extension is actually documented in their README at https://github.com/ubuntu/gnome-shell-extension-appindicator?tab=readme-ov-file#missing-features:

> Tooltips: Not implemented in libappindicator nor in Unity and I've yet to see any indicator using it for anything relevant (KDE ones maybe?). Also, the GNOME designers decided not to have tooltips in the shell and I'd like to honor that decision.

I guess Arch-Update could now be an example of an indicator using tooltip for something relevant, but I also understand upstream's decision to honor Gnome's design on that front. 

I guess one could try to start a discussion on that matter in the extension's GitHub repo, but seeing the above, I'm doubting they will consider adding tooltip support :shrug:

**Comment by DeN-AlB** [comment] 2024-10-02 18:31
Thank you very much for investigating on this issue. I don't think that I'll start a discussion there. I'll take it as it is and live with this.

Thanks! :+1:

**Comment by Antiz96** [comment] 2024-10-06 17:53
Hey @DeN-AlB!

So I've been thinking about this over the week-end, trying to find a solution to not let Gnome users on the side (despite Gnome not supporting systrays out of the box and the systray extension not supporting tooltips)...  
And the good news is, I was able to find what I personally think would be a solid alternative solution!

So the idea is to add (in addition of the dynamic tooltip) an extra dynamic entry in the context menu containing the current state of the system and a submenu containing the list of pending updates (if there are some available)

Here's what that would look like:

![2024-10-06_17-49](https://github.com/user-attachments/assets/77917cf1-ed40-448a-80d2-10e231bcc6ab)

![2024-10-06_17-48](https://github.com/user-attachments/assets/d7490457-6cdb-4763-978d-af44f757db2d)

As this is directly integrated in the context menu (and not using the tooltip), it should be visible to Gnome users :crossed_fingers: 
This way Gnome users will be able to see the list of pending updates without necessarily having to run Arch-Update (and it also gives an alternative way for non-Gnome users to see the list of pending updates). 

How does that sounds? :slightly_smiling_face:

**Closed** 2024-10-06 20:29 UTC
Labels: feature/request, not a bug

**Comment by Antiz96** [comment] 2024-10-06 20:33
> [...]
> How does that sounds? 🙂

Well, I found it cool so I merged it already :innocent:  

I'll release `v3.3.0` later this evening (including this new feature)!
Hopefully it'll be a good alternative to the tooltip for you (and other Gnome users) :smile:

**Comment by DeN-AlB** [comment] 2024-10-07 07:05
> How does that sounds? 🙂

Great idea! :+1: 

And it looks really great so far.

![image](https://github.com/user-attachments/assets/660caa88-f541-464e-b349-5606d1759c55)

That's what I wanted. Thanks a lot. :heart:

**Comment by Antiz96** [comment] 2024-10-07 07:10
> That's what I wanted. Thanks a lot. ❤️

So cool! I'm really glad that it works as intended on Gnome and that you like it.

Thanks a lot for the kind words and for your support! :pray: :heart:
