### ISSUE TITLE
Wrong return for flatpaks packages when an app uses an outdated runtime

### ISSUE THREAD

**Issue by swyknox** [Antiz96/arch-update#103] opened 2024-02-02 23:53 UTC
When a flatpak program uses an outdated runtime, the `flatpak update` command returns the following warning:
![Screnshot-2024-02-02-20-48-29](https://github.com/Antiz96/arch-update/assets/52772425/a3500dc1-e2ce-42eb-b4fe-6f4cd004b9d9)
What returns a possible error in arch-update:
![Screnshot-2024-02-02-20-50-59](https://github.com/Antiz96/arch-update/assets/52772425/f628cf2d-5356-476d-85c6-482322b211a4)

This is a problem (for me at least), because I use a waybar module that uses arch-update feedback to show the number of available updates, in this case, even without updates for the flatpak, I receive a false alert for this, due to printed lines that do not correspond to packages.

**Comment by Antiz96** [comment] 2024-02-04 15:20
Hi,

Thanks for the report!
The way `Arch-Update` extracts the list of pending Flatpak updates is a bit hacky*-ish* as the Flatpak CLI doesn't provide an simple/easy way to get it unfortunately... But hopefully I'll still be able to find a workaround around that issue :smile: 

Do you know a Flatpak package that triggers that warning currently? Being able to reproduce the issue on my side would help to tackle it.

**Comment by swyknox** [comment] 2024-02-06 07:15
Hello, thank you for your attention!
I understand that the extraction of information has to be done in an unconventional way due to limitations on the part of the Flatpak CLI.
Currently, the package [io.github.swanux.hbud](https://flathub.org/apps/io.github.swanux.hbud) is using an outdated runtime which gives the error shown above. I hope it can be useful for your analysis, see you soon!

**Comment by Antiz96** [comment] 2024-02-07 19:22
Hi,

I found a way to make the Flatpak packages updates detection more robust to avoid such false positives.
I pushed the fix in https://github.com/Antiz96/arch-update/pull/104/commits/ec8a61c1add94877cce05f73b3ea9cf83f354b1a.

With that above fix, everything located above the actual listing of available updates during `flatpak update` is dismissed so whatever is before that cannot be included in Arch-Update's listing anymore ;)

However, since this issue is fairly specific, I'll probably won't tag a new release just for that fix. There are still some work in progress I'd like to finish before releasing a new version. So this fix will be included in `v1.11.0` once it is ready.

In the mean time you can patch the script yourself locally on your machine to fix the issue on your side (it's only 3 lines to modify).
Don't hesitate to ask if you need help to do that :slightly_smiling_face: 

Thanks once again for the bug report!

**Closed** 2024-02-07 19:27 UTC
Labels: bug

**Comment by Antiz96** [comment] 2024-02-07 19:44
Hi,

I found a way to make the Flatpak packages updates detection more robust to avoid such false positives.
I pushed the fix in https://github.com/Antiz96/arch-update/pull/104/commits/ec8a61c1add94877cce05f73b3ea9cf83f354b1a.

With that fix, everything located above the actual listing of available updates during `flatpak update` is dismissed so whatever is before that cannot be included in Arch-Update's listing anymore. :wink: 

Since this issue is fairly specific, I'll probably won't tag a new release just for that though. There are still some work in progress I'd like to finish before releasing a new version.

However, I'll patch the [Arch-Update AUR package](https://aur.archlinux.org/packages/arch-update) with the fix in a moment, so if you're using it you'll get the fix in a minute *(otherwise, you can still patch the script yourself locally, it's only 3 lines to modify)*. :slightly_smiling_face: 

Thanks once again for the bug report!

**Comment by Antiz96** [comment] 2024-02-07 19:54
Arch-Update AUR package [patched](https://aur.archlinux.org/cgit/aur.git/commit/?h=arch-update&id=f6966f2c85f845cae6e36d05be677bd3a43ecffc) :wink:

**Comment by swyknox** [comment] 2024-02-11 13:29
Perfect, great work, I'm happy to help! 🚀
